"""Explicit field coverage for the strict rasim-simulation-v2 configuration."""

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class SimulationField:
    path: str
    label: str
    kind: str
    unit: str
    domain: str
    description: str
    default: object = None
    optional: bool = False
    choices: tuple[str, ...] = ()
    applicability: str = "All configured routes"


SIMULATION_FIELDS = (
    SimulationField(
        "material.cif_path",
        "Material CIF",
        "text",
        "path",
        "existing CIF",
        "Canonical crystal bytes; relative to imported configuration",
    ),
    SimulationField(
        "material.phase_id",
        "Phase identity",
        "text",
        "identifier",
        "nonempty",
        "Declared phase identity; no inferred specimen",
    ),
    SimulationField(
        "source.mean_origin_lab_m",
        "Mean source origin",
        "vector3",
        "m LAB",
        "finite",
        "Point in laboratory frame",
    ),
    SimulationField(
        "source.mean_direction_lab",
        "Mean beam direction",
        "vector3",
        "dimensionless LAB",
        "unit direction",
        "Propagation direction, independently of origin",
    ),
    SimulationField(
        "source.transverse_axes_lab",
        "Transverse axes",
        "axes",
        "dimensionless LAB",
        "orthonormal transverse triad",
        "Rows are the two source transverse axes",
    ),
    SimulationField(
        "source.spatial_sigma_m",
        "Spatial standard deviations",
        "vector2",
        "m",
        "nonnegative",
        "Source transverse position widths",
    ),
    SimulationField(
        "source.divergence_sigma_rad",
        "Divergence standard deviations",
        "vector2",
        "rad",
        "nonnegative",
        "Angular widths along the transverse axes",
    ),
    SimulationField(
        "source.position_divergence_correlation",
        "Position / divergence correlation",
        "vector2",
        "dimensionless",
        "strictly (-1,1)",
        "One correlation per transverse axis",
        [0.0, 0.0],
        True,
    ),
    SimulationField(
        "source.wavelength_model_id",
        "Spectrum law",
        "choice",
        "identifier",
        "supported law",
        "Discrete-line masses remain exact; no renormalization",
        "gaussian.v1",
        True,
        ("gaussian.v1", "discrete_gaussian_lines.v1"),
    ),
    SimulationField(
        "source.mean_wavelength_A",
        "Mean wavelength",
        "float",
        "angstrom",
        "positive; discrete centroid",
        "Must equal the declared discrete-line probability centroid",
    ),
    SimulationField(
        "source.wavelength_sigma_A",
        "Gaussian wavelength width",
        "float",
        "angstrom",
        "nonnegative; zero for discrete",
        "Gaussian spectrum width",
    ),
    SimulationField(
        "source.line_wavelength_A",
        "Line wavelengths",
        "sequence",
        "angstrom",
        "distinct positive, at least two",
        "One row per discrete spectral line",
        [],
        True,
        applicability="Discrete spectrum; empty or omitted for Gaussian",
    ),
    SimulationField(
        "source.line_probability",
        "Line probabilities",
        "sequence",
        "probability mass",
        "positive, sum one within 2e-15",
        "Exact independent wavelength masses",
        [],
        True,
        applicability="Discrete spectrum; empty or omitted for Gaussian",
    ),
    SimulationField(
        "source.common_line_sigma_A",
        "Common line width",
        "float",
        "angstrom",
        "nonnegative",
        "Width within each discrete line",
        0.0,
        True,
        applicability="Discrete spectrum; omit for Gaussian",
    ),
    SimulationField(
        "source.sample_count",
        "Physical source count",
        "int",
        "source rows",
        "positive; at least one per line",
        "Canonical source ensemble size, distinct from detector MC draws",
    ),
    SimulationField(
        "source.seed",
        "Source realization seed",
        "int",
        "unsigned 64-bit",
        "0 <= seed < 2**64",
        "Source realization only; detector seed is a separate run control",
    ),
    SimulationField(
        "source.polarization_state_id",
        "Polarization state",
        "text",
        "identifier",
        "canonical supported state",
        "Canonical polarization model; validated by its owner",
    ),
    SimulationField(
        "instrument.axis_rotations",
        "Goniometer axes / pivots",
        "rotations",
        "LAB; deg / m",
        "rigid active rotations",
        "Variable rows: axis XYZ, angle degrees, pivot XYZ",
    ),
    SimulationField(
        "instrument.detector_tilt.about_column_axis_deg",
        "Detector column-axis tilt",
        "float",
        "deg",
        "finite",
        "Applied once after base detector rotation",
        0.0,
        True,
    ),
    SimulationField(
        "instrument.detector_tilt.about_row_axis_deg",
        "Detector row-axis tilt",
        "float",
        "deg",
        "finite",
        "Applied once after base detector rotation",
        0.0,
        True,
    ),
    SimulationField(
        "instrument.detector_shape_rc",
        "Detector rows / columns",
        "integer_vector2",
        "pixels",
        "positive integers",
        "Native array shape [row,column]; never reduced for preview",
    ),
    SimulationField(
        "instrument.detector_row_pitch_m",
        "Row pixel pitch",
        "float",
        "m",
        "positive",
        "Native row-axis calibration",
    ),
    SimulationField(
        "instrument.detector_column_pitch_m",
        "Column pixel pitch",
        "float",
        "m",
        "positive",
        "Native column-axis calibration",
    ),
    SimulationField(
        "instrument.detector_reference_coordinate_px",
        "Detector reference column / row",
        "vector2",
        "px",
        "finite",
        "Continuous (column_px,row_px), not array index order",
    ),
    SimulationField(
        "instrument.sample_support_model_id",
        "Sample support",
        "text",
        "identifier",
        "canonical supported model",
        "Finite support is not available to conditional-position MC",
    ),
    SimulationField(
        "instrument.sample_width_m",
        "Sample width",
        "nullable_float",
        "m",
        "null or positive",
        "Declared support dimension; blank means null",
    ),
    SimulationField(
        "instrument.sample_length_m",
        "Sample length",
        "nullable_float",
        "m",
        "null or positive",
        "Declared support dimension; blank means null",
    ),
    SimulationField(
        "instrument.film_thickness_A",
        "Film thickness",
        "float",
        "angstrom",
        "nonnegative",
        "Uniform-depth attenuation thickness",
    ),
    SimulationField(
        "instrument.detector_path_medium_id",
        "Detector-path medium",
        "text",
        "identifier",
        "canonical attenuation declaration",
        "External Beer-Lambert path absorption",
        "vacuum_or_helium_unity.v1",
        True,
    ),
    SimulationField(
        "instrument.detector_path_linear_attenuation_m_inv",
        "Scalar path attenuation",
        "float",
        "m^-1",
        "nonnegative",
        "Applied once on external detector path",
        0.0,
        True,
    ),
    SimulationField(
        "instrument.detector_path_wavelength_A",
        "Attenuation wavelengths",
        "sequence",
        "angstrom",
        "positive exact source wavelengths",
        "Exact-wavelength table, not interpolated",
        [],
        True,
    ),
    SimulationField(
        "instrument.detector_path_linear_attenuation_m_inv_by_wavelength",
        "Tabulated path attenuation",
        "sequence",
        "m^-1",
        "nonnegative, matching wavelength rows",
        "Requires zero-width spectrum and every line plus centroid",
        [],
        True,
    ),
    SimulationField(
        "mosaic.gaussian_sigma_deg",
        "Gaussian mosaic width",
        "float",
        "deg",
        "positive if active",
        "Declared spherical mosaic probability component",
    ),
    SimulationField(
        "mosaic.lorentzian_hwhm_deg",
        "Lorentzian mosaic HWHM",
        "float",
        "deg",
        "positive if active",
        "Declared spherical Lorentzian component",
    ),
    SimulationField(
        "mosaic.lorentzian_probability",
        "Lorentzian probability",
        "float",
        "probability mass",
        "[0,1]",
        "Independent component mixture mass",
    ),
    SimulationField(
        "mosaic.alpha_panel_count",
        "Mosaic alpha panels",
        "int",
        "panels",
        "positive",
        "Canonical mosaic quadrature",
    ),
    SimulationField(
        "mosaic.alpha_gauss_order",
        "Mosaic alpha Gauss order",
        "int",
        "nodes",
        "positive",
        "Canonical mosaic quadrature",
    ),
    SimulationField(
        "mosaic.azimuth_count",
        "Mosaic azimuth count",
        "int",
        "nodes",
        "positive",
        "Canonical mosaic quadrature",
    ),
    SimulationField(
        "mosaic.azimuth_phase_deg",
        "Mosaic azimuth phase",
        "float",
        "deg",
        "finite",
        "Spin-grid phase; not acquisition angle",
    ),
    SimulationField(
        "structure_factor.model_id",
        "Structure model",
        "choice",
        "identifier",
        "supported model",
        "Generic CIF admission does not provide full-image MC",
        choices=(
            "r3m_quintuple_finite_2h.v1",
            "r3m_quintuple_finite_3r.v1",
            "cif_conventional_cell_finite_repeat.v1",
        ),
    ),
    SimulationField(
        "structure_factor.layers",
        "Quintuple layers",
        "int",
        "layers",
        "positive",
        "Finite R-3m stack depth",
        50,
        True,
        applicability="Finite quintuple stack; omit for generic CIF",
    ),
    SimulationField(
        "structure_factor.repeats",
        "Conventional-cell repeats",
        "int",
        "repeats",
        "positive",
        "Finite conventional-cell repeat count",
        1,
        True,
        applicability="Generic CIF; omit for quintuple stacks",
    ),
    SimulationField(
        "structure_factor.normalization",
        "Structure normalization",
        "choice",
        "identifier",
        "selected-model constraint",
        "Quintuple stacks require FINITE_TOTAL",
        choices=("FINITE_TOTAL", "FINITE_PER_LAYER"),
    ),
    SimulationField(
        "structure_factor.shared_disorder_epsilon",
        "Disorder epsilon",
        "float",
        "probability",
        "[0,1]; zero for generic CIF",
        "Existing shared transition law, not a new disorder model",
        0.0,
        True,
    ),
    SimulationField(
        "structure_factor.unknown_u_iso_A2",
        "Unknown isotropic displacement",
        "nullable_float",
        "angstrom^2",
        "null or nonnegative",
        "Explicit assumption for CIF sites lacking ADPs",
        None,
        True,
        applicability="Generic CIF; omit for quintuple stacks",
    ),
    SimulationField(
        "bragg.selection_model",
        "Physical rod selection",
        "choice",
        "identifier",
        "all elastic reachable",
        "No display-based reflection pruning",
        choices=("all_elastic_reachable.v1",),
    ),
    SimulationField(
        "bragg.rod_population",
        "Rod population",
        "float",
        "intensity weight",
        "nonnegative",
        "One population per retained physical rod",
    ),
    SimulationField(
        "bragg.include_detector_visible_m0",
        "Include detector-visible m=0",
        "bool",
        "boolean",
        "true or false",
        "Retain declared regular m=0 support",
    ),
    SimulationField(
        "bragg.root_policy",
        "Elastic root policy",
        "choice",
        "identifier",
        "all retained roots",
        "Canonical root classification and branch support",
        choices=("all_retained_roots.v1",),
    ),
    SimulationField(
        "weights.phase_population",
        "Phase population",
        "float",
        "intensity weight",
        "nonnegative",
        "Independent phase intensity weight, applied once",
    ),
    SimulationField(
        "weights.polarization",
        "Polarization weight",
        "float",
        "intensity weight",
        "nonnegative",
        "Additional declared polarization population, applied once",
    ),
    SimulationField(
        "numerics.worker_count",
        "CPU worker limit",
        "int",
        "workers",
        "positive; desktop run cap 4",
        "Explicit CPU execution limit; nested BLAS threads capped separately",
    ),
    SimulationField(
        "numerics.detector_execution_backend",
        "Detector backend",
        "choice",
        "identifier",
        "cpu or cuda",
        "Explicit selection; unavailable CUDA fails without fallback",
        choices=("cpu", "cuda"),
    ),
    SimulationField(
        "numerics.detector_macrobin_size_px",
        "Display macrobin size",
        "int",
        "pixels",
        "positive divisor of both axes",
        "Macrobin mass is a display preview, not native pixel mass",
    ),
    SimulationField(
        "numerics.detector_gauss_order",
        "Detector Gauss order",
        "int",
        "nodes",
        "positive even",
        "Even order avoids center caustics",
    ),
    SimulationField(
        "numerics.reciprocal_alpha_count",
        "Reciprocal alpha count",
        "int",
        "nodes",
        "positive",
        "Reciprocal display sampling",
    ),
    SimulationField(
        "numerics.reciprocal_beta_count",
        "Reciprocal beta count",
        "int",
        "nodes",
        "positive",
        "Reciprocal display sampling",
    ),
    SimulationField(
        "numerics.reciprocal_u_count",
        "Reciprocal longitudinal count",
        "int",
        "nodes",
        "positive",
        "Reciprocal display sampling",
    ),
    SimulationField(
        "numerics.reciprocal_alpha_max_deg",
        "Reciprocal alpha extent",
        "float",
        "deg",
        "positive <=180",
        "Display sampling support; not reflection pruning",
    ),
    SimulationField(
        "numerics.ewald_alpha_count",
        "Ewald alpha count",
        "int",
        "nodes",
        "positive",
        "Nominal Ewald coating sampling",
    ),
    SimulationField(
        "numerics.ewald_beta_count",
        "Ewald beta count",
        "int",
        "nodes",
        "positive",
        "Nominal Ewald coating sampling",
    ),
    SimulationField(
        "numerics.ewald_alpha_max_deg",
        "Ewald alpha extent",
        "float",
        "deg",
        "positive <=180",
        "Nominal Ewald coating sampling support",
    ),
    SimulationField(
        "outputs.output_directory",
        "Output directory",
        "text",
        "external path",
        "outside Git checkouts",
        "No automatic write on an edit or run",
    ),
    SimulationField(
        "outputs.reciprocal_space.enabled",
        "Select reciprocal output",
        "bool",
        "boolean",
        "true or false",
        "Explicit configured output selection",
    ),
    SimulationField(
        "outputs.reciprocal_space.filename",
        "Reciprocal output name",
        "text",
        "filename",
        "canonical artifact filename",
        "Requested reciprocal figure filename",
    ),
    SimulationField(
        "outputs.ewald_surface.enabled",
        "Select Ewald output",
        "bool",
        "boolean",
        "true or false",
        "Explicit configured output selection",
    ),
    SimulationField(
        "outputs.ewald_surface.filename",
        "Ewald output name",
        "text",
        "filename",
        "canonical artifact filename",
        "Requested Ewald figure filename",
    ),
    SimulationField(
        "outputs.detector.enabled",
        "Select detector output",
        "bool",
        "boolean",
        "true or false",
        "Explicit configured output selection",
    ),
    SimulationField(
        "outputs.detector.filename",
        "Detector output name",
        "text",
        "filename",
        "canonical artifact filename",
        "Requested detector figure filename",
    ),
    *(
        SimulationField(
            f"instrument.{name}.rotation",
            label + " rotation",
            "matrix",
            "active column-vector",
            "SO(3)",
            "Full declared rigid rotation matrix",
        )
        for name, label in (
            ("lab_from_goniometer_zero", "LAB from goniometer zero"),
            ("goniometer_from_sample", "Goniometer from sample"),
            ("sample_from_crystal", "Sample from crystal"),
            ("lab_from_detector", "LAB from detector"),
        )
    ),
    *(
        SimulationField(
            f"instrument.{name}.translation_m",
            label + " translation",
            "vector3",
            "m target frame",
            "finite",
            "Full declared rigid point translation",
        )
        for name, label in (
            ("lab_from_goniometer_zero", "LAB from goniometer zero"),
            ("goniometer_from_sample", "Goniometer from sample"),
            ("sample_from_crystal", "Sample from crystal"),
            ("lab_from_detector", "LAB from detector"),
        )
    ),
)
