"""Continuous and finite-bin detector-to-angle observables."""

from rasim_next.measurement.angle_space import (
    AngleBinGrid,
    IncreasingPhiAngleField,
    NormalizedAngleField,
    NormalizedAngleProfiles,
    SparseDetectorAngleProjector,
    SparseDetectorProfileProjector,
    compile_detector_angle_projector,
    compile_detector_profile_projector,
    project_detector_profiles,
    project_normalized_angle_field,
    to_increasing_phi,
)
from rasim_next.measurement.continuous_angle import (
    ContinuousNormalizedAngleFunction,
    ContinuousNormalizedAngleValues,
    ContinuousPerRodAngleValues,
    evaluate_continuous_per_rod_angle_signal,
)
from rasim_next.measurement.continuous_regions import (
    COUNT_VARIANCE_FLOOR_COUNT,
    ContinuousDetectorAreaChart,
    ContinuousDetectorChartAreaMeasure,
    ContinuousRegionQuadrature,
    NativePixelRegionProjection,
    compile_continuous_rectangle_quadrature,
    compile_native_pixel_region_projection,
    integrate_shared_native_pixel_field,
)
from rasim_next.measurement.reciprocal_profiles import (
    BinnedSampleIntegral,
    LayeredReciprocalFrame,
    ReciprocalProfileMembership,
    ReciprocalProfileRegion,
    accumulate_binned_samples,
    reciprocal_profile_membership,
)
from rasim_next.measurement.region_observations import (
    OffSpecularBand,
    OffSpecularBandLayout,
    OffSpecularMembership,
    SpecularAngularMembership,
    SpecularAngularProfileRegion,
    offspecular_region_membership,
    specular_angular_membership,
)

__all__ = [
    "COUNT_VARIANCE_FLOOR_COUNT",
    "AngleBinGrid",
    "BinnedSampleIntegral",
    "ContinuousDetectorAreaChart",
    "ContinuousDetectorChartAreaMeasure",
    "ContinuousNormalizedAngleFunction",
    "ContinuousNormalizedAngleValues",
    "ContinuousPerRodAngleValues",
    "ContinuousRegionQuadrature",
    "IncreasingPhiAngleField",
    "LayeredReciprocalFrame",
    "NativePixelRegionProjection",
    "NormalizedAngleField",
    "NormalizedAngleProfiles",
    "OffSpecularBand",
    "OffSpecularBandLayout",
    "OffSpecularMembership",
    "ReciprocalProfileMembership",
    "ReciprocalProfileRegion",
    "SparseDetectorAngleProjector",
    "SparseDetectorProfileProjector",
    "SpecularAngularMembership",
    "SpecularAngularProfileRegion",
    "accumulate_binned_samples",
    "compile_continuous_rectangle_quadrature",
    "compile_detector_angle_projector",
    "compile_detector_profile_projector",
    "compile_native_pixel_region_projection",
    "evaluate_continuous_per_rod_angle_signal",
    "integrate_shared_native_pixel_field",
    "offspecular_region_membership",
    "project_detector_profiles",
    "project_normalized_angle_field",
    "reciprocal_profile_membership",
    "specular_angular_membership",
    "to_increasing_phi",
]
