"""Detector-native geometric fitting interfaces."""

from rasim_next.fitting.geometry import (
    ContinuousDetectorFunction,
    ContinuousDetectorGeometryModel,
    GeometryCorrectionBounds,
    GeometryCorrections,
    GeometryFitResult,
    GeometryPredictionError,
    GeometryRankError,
    IntegerLGeometryModel,
    IntegerLMarkerKey,
    IntegerLMarkerObservations,
    IntegerLMarkerPrediction,
    IntegerLSelectionAudit,
    M0IntegerLObservations,
    M0IntegerLPrediction,
    audit_integer_l_marker_selection,
    evaluate_tagged_geometry_objective_residual,
    fit_integer_l_marker_geometry,
    fit_tagged_detector_function_geometry,
)

__all__ = [
    "ContinuousDetectorFunction",
    "ContinuousDetectorGeometryModel",
    "GeometryCorrectionBounds",
    "GeometryCorrections",
    "GeometryFitResult",
    "GeometryPredictionError",
    "GeometryRankError",
    "IntegerLGeometryModel",
    "IntegerLMarkerKey",
    "IntegerLMarkerObservations",
    "IntegerLMarkerPrediction",
    "IntegerLSelectionAudit",
    "M0IntegerLObservations",
    "M0IntegerLPrediction",
    "audit_integer_l_marker_selection",
    "evaluate_tagged_geometry_objective_residual",
    "fit_integer_l_marker_geometry",
    "fit_tagged_detector_function_geometry",
]
